# Generated by Django 4.2 on 2023-05-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('picture1', models.ImageField(upload_to='service_images')),
                ('picture2', models.ImageField(upload_to='service_images')),
            ],
        ),
    ]
