# Generated by Django 4.2 on 2023-05-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_alter_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='picture3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='service_images'),
        ),
        migrations.AddField(
            model_name='services',
            name='picture4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='service_images'),
        ),
        migrations.AddField(
            model_name='services',
            name='picture5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='service_images'),
        ),
        migrations.AddField(
            model_name='services',
            name='picture6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='service_images'),
        ),
    ]
