# Generated by Django 4.2 on 2023-05-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_services_picture3_services_picture4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landscping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('picture1', models.ImageField(upload_to='service_images')),
                ('picture2', models.ImageField(blank=True, default=None, null=True, upload_to='service_images')),
                ('picture3', models.ImageField(blank=True, default=None, null=True, upload_to='service_images')),
                ('picture4', models.ImageField(blank=True, default=None, null=True, upload_to='service_images')),
                ('picture5', models.ImageField(blank=True, default=None, null=True, upload_to='service_images')),
                ('icon', models.ImageField(upload_to='service_images')),
            ],
        ),
        migrations.CreateModel(
            name='Pruning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('picture1', models.ImageField(upload_to='service_images')),
                ('picture2', models.ImageField(blank=True, default=None, null=True, upload_to='service_images')),
                ('picture3', models.ImageField(blank=True, default=None, null=True, upload_to='service_images')),
                ('picture4', models.ImageField(blank=True, default=None, null=True, upload_to='service_images')),
                ('picture5', models.ImageField(blank=True, default=None, null=True, upload_to='service_images')),
                ('icon', models.ImageField(upload_to='service_images')),
            ],
        ),
    ]
