# Generated by Django 4.2 on 2023-05-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0005_planting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='picture2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='service_images'),
        ),
    ]
