# Generated by Django 4.2 on 2023-05-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_alter_services_picture2'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
