# Generated by Django 4.2 on 2023-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_services_description2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=54)),
                ('subject', models.CharField(max_length=50)),
                ('msgs', models.TextField()),
            ],
        ),
    ]
