# Generated by Django 4.2 on 2023-05-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=54)),
                ('phone', models.CharField(max_length=30)),
                ('service_type', models.CharField(max_length=50)),
                ('msgs', models.TextField()),
            ],
        ),
    ]
