# Generated by Django 4.2 on 2023-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0009_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
